### PR TITLE
Update Travis to Go 1.11

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**

### CODE REVIEW

**Comment by superwhiskers** [comment]
eyes

**Comment by hyarsan** [comment]
👀

**Comment by ThatNerdyPikachu** [comment]
(L- Josh knows about the differences more than we both do, feel free to review though)

**Comment by superwhiskers** [comment]
i know the differences too. there's only two big things added

**Comment by JoshuaDoes** [comment]
Looks fine to me

**Comment by ThatNerdyPikachu** [comment]
was just wondering why you had it at go 1.10 for some breaking change /shrug

**Comment by ThatNerdyPikachu** [comment]
sorry

**Comment by superwhiskers** [comment]
inb4 pr was only for hacktoberfest

**Comment by ThatNerdyPikachu** [comment]
it wasn't, stop >:(

**Comment by hyarsan** [comment]
.-.

**Comment by arkizenty** [comment]
oof

**Comment by hyarsan** [comment]
hey arki can you fix my bot k thx

**Comment by arkizenty** [comment]
oof

**Pull request merged**
